version: '3.4'

services:

  website:
    build: .
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    volumes:
      - '.:/app'
    env_file:
      - '.env'

#  cable:
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'
secrets:
  redis_cache_password:
    file: ./docker/secrets/redis_cache_password
  redis_sessions_password:
    file: ./docker/secrets/redis_sessions_password
  redis_jobs_password:
    file: ./docker/secrets/redis_jobs_password