version: '3.4'

services:

  website:
    build: .
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    volumes:
      - '.:/app'
    env_file:
      - '.env'

secrets:
  postgres_password:
    file: ./docker/secrets/postgres_password
  redis_cache_password:
    file: ./docker/secrets/redis_cache_password
  redis_sessions_password:
    file: ./docker/secrets/redis_sessions_password
  redis_jobs_password:
    file: ./docker/secrets/redis_jobs_password
