version: '3.4'

services:

  website:
    build: .
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  cable:
    volumes:
      - '.:/app'
    env_file:
      - '.env'
