---

<% uri = URI(ENV['POSTGRES_URL']) %>
<% uri.password = Rails.application.secrets.postgres_password %>

development: &default
  url: <%= uri.to_s %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
