---
<%
def docker_secret(pw)
  return unless File.exists?("/run/secrets/#{pw}")
  File.read("/run/secrets/#{pw}").chomp
end
%>
development: &default
  secret_key_base:         <%= docker_secret('rails_secret_token') %>
  redis_cache_password:    <%= docker_secret('redis_cache_password') %>
  redis_jobs_password:     <%= docker_secret('redis_jobs_password') %>
  redis_sessions_password: <%= docker_secret('redis_sessions_password') %>
  postgres_password:       <%= docker_secret('postgres_password')  %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
