---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  redis_cache_password: <%= ENV['REDIS_CACHE'] == 'yes' ? File.read('/run/secrets/redis_cache_password').chomp : '' %>
  redis_jobs_password: <%= File.read('/run/secrets/redis_jobs_password').chomp %>
  redis_sessions_password: <%= ENV['REDIS_SESSIONS'] == 'yes' ? File.read('/run/secrets/redis_sessions_password').chomp : '' %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
